// GENERATED by scripts/build-bot-context.mjs — do not edit by hand.

// src/data/about.json
var about_default = {
  title: "Hello, I'm Moieez ur Rehman.",
  subtitle: "Senior Full Stack Engineer & Software Architect",
  description: [
    "Product-focused Full Stack Engineer and Software Architect with {{experienceYears}} years of experience building scalable systems across retail and SaaS \u2014 from POS platforms to loyalty systems and customer engagement tools, ecommerce, payment integrations, booking systems, search-engine integrations, and dashboards. I work across the stack using React, Vue, Next.js, Node.js, and NestJS, delivering reliable, high-quality solutions with a strong focus on real-world usability.",
    "I take ownership of features end-to-end \u2014 from understanding business needs and structuring solutions to implementation and deployment \u2014 with a focus on writing maintainable code, improving system efficiency, and delivering software that creates measurable impact. Core strengths include POS retail systems, payment integrations (MyFatoorah, Moyasar), CRM, wallet integrations (Apple Wallet & Google Wallet), designing system architectures and helping teams execute on them, microservices and monorepo patterns, and leading UI/UX engineering.",
    "I've revamped and stabilized unstable applications, supported management teams, and improved products by solving real problems. Recent work includes POS platforms, loyalty systems, customer engagement tools, and OpenRouter AI (DeepSeek) for smart search and analysis \u2014 contributing to both technical architecture and product direction."
  ]
};

// src/utils/experience.js
var CAREER_START = new Date(2019, 4, 1);
function getExperienceYears(from = CAREER_START, to = /* @__PURE__ */ new Date()) {
  const months = (to.getFullYear() - from.getFullYear()) * 12 + (to.getMonth() - from.getMonth());
  const years = Math.floor(months / 12);
  return Math.max(0, years);
}
function withExperienceYears(text) {
  if (!text) return text;
  return String(text).replaceAll("{{experienceYears}}", String(getExperienceYears()));
}

// src/data/skills.json
var skills_default = [
  {
    category: "Core Skills",
    items: [
      "Product Ownership",
      "Feature Ownership",
      "Product Management",
      "Feature Management",
      "UI/UX Management",
      "End-to-End Delivery"
    ]
  },
  {
    category: "Architectures",
    items: [
      "System Design",
      "MVC",
      "HMVC",
      "MVP",
      "MVVM",
      "Component Based",
      "Microservices",
      "Event-driven architecture",
      "Monorepo"
    ]
  },
  {
    category: "Frontend",
    items: [
      "React",
      "NextJs",
      "Vue",
      "NuxtJs",
      "Zustand",
      "Redux Toolkit",
      "TanStack Query",
      "Context API",
      "Pinia",
      "Vuex",
      "TailwindCSS",
      "MaterialUI",
      "Bootstrap",
      "Buefy",
      "Jquery",
      "Flutter"
    ]
  },
  {
    category: "Backend",
    items: [
      "Node",
      "Express",
      "NestJS",
      "Fastify",
      "REST APIs",
      "ASP.NET",
      "DotNET",
      "Laravel",
      "PHP",
      "Entity Framework",
      "LINQ"
    ]
  },
  {
    category: "Databases",
    items: [
      "PostgreSQL",
      "MySQL",
      "SQL Server",
      "MongoDB",
      "Prisma",
      "Redis",
      "BullMQ"
    ]
  },
  {
    category: "Programming Languages",
    items: [
      "TypeScript",
      "JavaScript",
      "SQL",
      "HTML5",
      "CSS3",
      "SCSS",
      "C# (C Sharp)",
      "Python"
    ]
  },
  {
    category: "Performance & Security",
    items: [
      "Code Splitting",
      "Lazy Loading",
      "Caching",
      "Database Indexing",
      "RBAC",
      "OAuth2",
      "OIDC",
      "JWT",
      "SSO",
      "Authentication & Authorization"
    ]
  },
  {
    category: "Integrations",
    items: [
      "Webhooks",
      "CRM",
      "MyFatoorah",
      "Moyasar",
      "Apple Wallet",
      "Google Wallet",
      "Sabre",
      "Amadeus"
    ]
  },
  {
    category: "Tools & Platforms",
    items: [
      "Git",
      "GitHub",
      "GitLab",
      "Jira",
      "Trello",
      "Vite",
      "Vercel",
      "Netlify",
      "CI/CD",
      "Docker"
    ]
  },
  {
    category: "AI & Automation",
    items: [
      "OpenRouter",
      "DeepSeek",
      "Claude Code",
      "Cursor",
      "GitHub Copilot",
      "Agentic AI"
    ]
  },
  {
    category: "Collaboration",
    items: [
      "Agile Methodologies",
      "Scrum",
      "Test-Driven Development"
    ]
  },
  {
    category: "Design & Prototyping",
    items: [
      "Figma",
      "Adobe XD",
      "Sketch"
    ]
  }
];

// src/data/contacts.json
var contacts_default = [
  {
    platform: "WhatsApp",
    handle: "+966 573240913",
    categories: ["contact"],
    url: "https://wa.me/966573240913",
    icon: "/socialMediaIcons/Whatsapp.svg"
  },
  {
    platform: "LinkedIn",
    handle: "linkedin.com/in/moiezdev",
    categories: ["media", "contact", "portfolio"],
    url: "https://www.linkedin.com/in/moiezdev/",
    icon: "/socialMediaIcons/Linkedin.svg"
  },
  {
    platform: "Email",
    handle: "moiezdev@gmail.com",
    categories: ["contact"],
    url: "mailto:moiezdev@gmail.com",
    icon: "/socialMediaIcons/Email.svg"
  },
  {
    platform: "GitHub",
    handle: "@moiezdev",
    categories: ["media", "portfolio"],
    url: "https://github.com/moiezdev",
    icon: "/socialMediaIcons/Github.svg"
  },
  {
    platform: "Phone",
    handle: "+966 573240913",
    categories: ["contact"],
    url: "tel:+966573240913",
    icon: "/socialMediaIcons/Phone.svg"
  }
];

// src/data/chatbot.json
var chatbot_default = {
  botName: "BotFolio",
  profile: {
    name: "Moieez ur Rehman",
    alsoKnownAs: [
      "Moiz",
      "Moiez",
      "MoizDev",
      "MoiezDev"
    ],
    headline: "Senior Full Stack Engineer & Software Architect | Node.js/NestJS, React/Next.js, PostgreSQL, LLM integrations",
    location: "Riyadh, Saudi Arabia",
    careerStart: "2019-05-01",
    identity: "Product-focused Full Stack Engineer and Software Architect with experience across retail, travel and SaaS. Owns features end to end \u2014 from understanding the business problem to architecture, build, deploy and iteration. Designs systems (event-driven workflows, data access layers, auth/RBAC, background jobs) and ships them across web, mobile and integrations: POS and payments, loyalty and wallet passes, booking engines, e-commerce storefronts, internal dashboards, and AI features with OpenRouter/DeepSeek.",
    iqama: "Transferable Iqama \xB7 Available Immediately",
    portfolioUrl: "https://www.moiez.dev"
  },
  lowPriorityProjectIds: [
    "eims",
    "lms"
  ],
  projectNavKeywords: {
    "twlm-pos": [
      "twlm",
      "pos",
      "twlm pos",
      "twlm-pos",
      "twlm - pos",
      "loyalty",
      "wallet",
      "gift card",
      "openrouter",
      "deepseek",
      "ai",
      "menu search",
      "cms",
      "e-menu"
    ],
    "aa-tourism": [
      "aatourism",
      "aa tourism",
      "aa travel",
      "amadeus",
      "sabre"
    ],
    "gala-travels": [
      "gala",
      "hotel",
      "cruise",
      "vacation"
    ],
    "mian-travels": [
      "mian"
    ],
    scmborba: [
      "scmborba",
      "borba",
      "misericordia",
      "scm"
    ],
    "docean-fisheries": [
      "docean",
      "d'ocean",
      "fisheries",
      "seafood"
    ],
    "ain-saas": [
      "ain",
      "saiss",
      "saas"
    ],
    "city-arrivals": [
      "city arrivals",
      "luxury",
      "car rental",
      "limousine"
    ],
    mtlnation: [
      "mtlnation",
      "mtl"
    ],
    tdm: [
      "tdm",
      "engenharia"
    ],
    "my-portfolio": [
      "portfolio website",
      "this site",
      "moiez.dev",
      "chatbot",
      "botfolio"
    ],
    eims: [
      "eims",
      "lms",
      "learning",
      "course recommendation"
    ],
    lms: [
      "lms",
      "learning management"
    ]
  },
  audiences: {
    recruiters: {
      lookingFor: "Senior Full Stack Engineer / Software Architect roles (full-time) \u2014 Node.js/NestJS, React/Next.js, AI-integration work.",
      pitch: [
        "Senior full stack engineer who owns features end to end \u2014 architecture, backend, frontend and delivery.",
        "Proven impact: ~70% fewer support requests and ~64% lower API latency at TWLM; ~25% less downtime at ACCIONA; B2B travel platforms serving 10K+ monthly users.",
        "Built production integrations recruiters in the Gulf care about: MyFatoorah and Moyasar payments, Apple/Google Wallet, Sabre/Amadeus booking engines, OpenRouter/DeepSeek LLMs.",
        "Based in Riyadh and building for the Gulf market; transferable Iqama, available immediately."
      ],
      nextSteps: "CV at /cv, email moiezdev@gmail.com, WhatsApp +966 573240913, LinkedIn linkedin.com/in/moiezdev."
    },
    clients: {
      openTo: "Freelance and contract product work alongside full-time roles: new builds, rescuing or scaling existing apps, integrations and AI features.",
      canBuild: [
        "Web apps and SaaS platforms (React/Next.js or Vue/Nuxt front ends, Node.js/NestJS APIs, PostgreSQL)",
        "POS, ordering, loyalty, gift cards and Apple/Google Wallet passes",
        "Payments with Gulf gateways (MyFatoorah, Moyasar) and webhook-driven workflows",
        "Booking and travel engines (Sabre, Amadeus), e-commerce storefronts and CMS/page builders",
        "Internal dashboards, reporting and admin tools with RBAC/SSO",
        "AI features: LLM search, assistants and data analysis via OpenRouter/DeepSeek",
        "Mobile apps with Flutter (as part of a product)"
      ],
      howHeWorks: [
        "Understand: the business goal, users and constraints first.",
        "Architect: data models, APIs and service boundaries that stay clean as the product grows.",
        "Build: typed, tested, maintainable code across frontend, backend and integrations.",
        "Ship & measure: deploy, monitor and iterate on real usage."
      ],
      toStart: "Share what you're building, who it's for, the must-have features and your timeline via the Contact page, email or WhatsApp \u2014 he replies within 24 hours. Pricing and timelines are discussed directly with him."
    }
  }
};

// src/data/experience.json
var experience_default = [
  {
    id: "twlm",
    title: "Senior Software Engineer \xB7 Full Stack",
    company: "TWLM",
    location: "Saudi Arabia",
    period: "Feb 2025 \u2013 Present",
    current: true,
    companyUrl: "https://twlm.solutions/",
    logo: "/company-logos/twlm.svg",
    summary: "Restaurant POS, loyalty, wallets and AI search for Gulf retail \u2014 designed and built from architecture to production.",
    stack: [
      "React",
      "NestJS",
      "Prisma",
      "PostgreSQL",
      "BullMQ",
      "Redis",
      "Flutter",
      "Apple Wallet",
      "Google Wallet",
      "OpenRouter"
    ],
    relatedProjects: [
      "twlm-pos"
    ],
    highlights: [
      "Designed and built a restaurant POS platform with integrated loyalty, promotions and wallet features, from architecture through production delivery.",
      "Built a block-based page builder that lets businesses create and manage their own menus and e-commerce storefronts without developer help.",
      "Reworked core user flows based on support data, reducing customer support requests by ~70%.",
      "Implemented four loyalty features (points, loyalty passes, gift cards and discount coupons) with Apple Wallet and Google Wallet passes and real-time updates.",
      "Built a geo-targeted promotional messaging system with branch-level campaign tracking.",
      "Optimized backend performance, reducing API response times by ~64%.",
      "Set up the data layer with Prisma ORM and PostgreSQL, including schema migrations and query optimization.",
      "Implemented RBAC and OAuth2/JWT authentication with SSO for multi-role access across the platform.",
      "Built webhook-driven, event-based workflows with Redis-backed BullMQ workers to process notification and wallet-update jobs asynchronously.",
      "Integrated CRM and leasing platforms to keep customer and business data in sync.",
      "Integrated OpenRouter AI (DeepSeek) to add smart menu search and AI-based analysis of restaurant data."
    ]
  },
  {
    id: "accoina",
    title: "Senior Software Engineer",
    company: "ACCIONA",
    location: "Saudi Arabia",
    period: "Jan 2024 \u2013 Feb 2025",
    current: false,
    companyUrl: "https://www.acciona.com/",
    logo: "/company-logos/acciona.jpg",
    logoOnLight: true,
    summary: "Internal tools and dashboards that digitized operations and cut downtime.",
    stack: [
      "React",
      "SQL",
      "RBAC",
      "OAuth2",
      "JWT"
    ],
    relatedProjects: [],
    highlights: [
      "Improved internal operations by digitizing workflows and reducing system downtime by ~25%.",
      "Built internal dashboards for reporting and analytics using React and SQL.",
      "Maintained and extended backend services and APIs for internal tools.",
      "Implemented RBAC and OAuth2/JWT-based authentication for internal dashboards and tools.",
      "Identified and resolved system bottlenecks, improving performance and ensuring smoother day-to-day operations.",
      "Automated routine processes and reporting tasks, increasing efficiency and reducing manual workload."
    ]
  },
  {
    id: "scm-borba",
    title: "Senior Frontend Engineer",
    company: "Santa Casa da Miseric\xF3rdia de Borba (SCM Borba)",
    location: "Portugal (Remote)",
    period: "Oct 2022 \u2013 Jan 2024",
    current: false,
    companyUrl: "https://www.scmborba.pt/pt",
    logo: "/company-logos/scm-borba.jpg",
    logoOnLight: true,
    summary: "8+ SaaS, e-commerce, and education builds delivered remotely.",
    stack: [
      "React",
      "Vue",
      "NuxtJs",
      "Node",
      "Express",
      "TailwindCSS"
    ],
    relatedProjects: [
      "scmborba"
    ],
    highlights: [
      "Delivered 8+ projects across SaaS, e-commerce, and education platforms.",
      "Built scalable, high-performance UIs using React, Vue, Nuxt, and Tailwind.",
      "Developed and integrated REST APIs using Node.js and Express.",
      "Improved application performance using code-splitting, lazy loading, and optimized rendering.",
      "Deployed applications using CI/CD pipelines (GitLab) and platforms like Vercel.",
      "Implemented OAuth2/JWT-based authentication and SSO integration for client platforms.",
      "Translated Figma/XD designs into production-ready, responsive interfaces.",
      "Collaborated directly with clients to understand requirements and translate business needs into scalable technical solutions.",
      "Debugged complex production issues and provided optimized solutions, improving system reliability and user experience.",
      "Built reusable components and modular architectures, reducing development time and improving maintainability across projects."
    ]
  },
  {
    id: "creative-inter-tech",
    title: "Frontend Engineer \u2192 Senior Frontend Engineer",
    company: "Creative Inter Tech",
    location: "Faisalabad, Pakistan",
    period: "Mar 2020 \u2013 Oct 2022",
    current: false,
    companyUrl: "https://creativeintertech.com/",
    logo: "/company-logos/cit.svg",
    summary: "Led frontend for B2B travel platforms serving 10K+ monthly users.",
    stack: [
      "React",
      "Vue",
      "Redux Toolkit",
      "Vuex",
      "RBAC",
      "Laravel"
    ],
    relatedProjects: [
      "aa-tourism",
      "city-arrivals",
      "gala-travels"
    ],
    highlights: [
      "Led frontend for B2B travel platforms (AA Tourism, City Arrivals) serving 10K+ monthly users.",
      "Built reusable component libraries in React/Vue, cutting dev time by ~30%.",
      "Collaborated in Agile teams, improving UX and boosting user retention by 15%.",
      "Upgraded legacy projects with React/Vue, improving responsiveness by 25%.",
      "Applied Redux, Vuex, and hooks for scalable state management, reducing data-related bugs by 40%.",
      "Implemented role-based access control (RBAC) for platform user permissions and admin workflows.",
      "Enhanced performance with React.memo and render optimizations."
    ]
  },
  {
    id: "content-arcade",
    title: "Web Developer",
    company: "Content Arcade",
    location: "Faisalabad, Pakistan",
    period: "May 2019 \u2013 Mar 2020",
    current: false,
    companyUrl: "https://www.contentarcade.com/",
    logo: "/company-logos/content-arcade.png",
    logoWide: true,
    summary: "First professional role \u2014 responsive layouts and PHP/Laravel APIs.",
    stack: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "PHP",
      "Laravel",
      "MySQL"
    ],
    relatedProjects: [],
    highlights: [
      "Built responsive layouts using HTML, CSS, and Bootstrap.",
      "Supported backend with PHP, Laravel, and MySQL APIs (CRUD).",
      "Performed bug fixes and cross-browser testing, improving stability."
    ]
  }
];

// src/data/education.json
var education_default = {
  degree: "BSCS Hons \u2013 Bachelor of Science in Computer Science",
  school: "National College of Business Administration & Economics, Lahore",
  period: "2017\u20132021",
  languages: [
    "English (Fluent)",
    "Urdu (Native)",
    "Hindi (Native)"
  ]
};

// src/data/events.json
var events_default = [
  {
    id: "leap-2026",
    name: "LEAP 2026",
    place: {
      en: "Riyadh, Saudi Arabia",
      ar: "\u0627\u0644\u0631\u064A\u0627\u0636\u060C \u0627\u0644\u0645\u0645\u0644\u0643\u0629 \u0627\u0644\u0639\u0631\u0628\u064A\u0629 \u0627\u0644\u0633\u0639\u0648\u062F\u064A\u0629"
    },
    summary: {
      en: "At one of the world's largest tech events \u2014 exploring AI infrastructure, robotics and cloud platforms with the teams building them.",
      ar: "\u0641\u064A \u0648\u0627\u062D\u062F\u0629 \u0645\u0646 \u0623\u0643\u0628\u0631 \u0627\u0644\u0641\u0639\u0627\u0644\u064A\u0627\u062A \u0627\u0644\u062A\u0642\u0646\u064A\u0629 \u0641\u064A \u0627\u0644\u0639\u0627\u0644\u0645 \u2014 \u0627\u0633\u062A\u0643\u0634\u0627\u0641 \u0627\u0644\u0628\u0646\u0649 \u0627\u0644\u062A\u062D\u062A\u064A\u0629 \u0644\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064A \u0648\u0627\u0644\u0631\u0648\u0628\u0648\u062A\u0627\u062A \u0648\u0627\u0644\u0645\u0646\u0635\u0627\u062A \u0627\u0644\u0633\u062D\u0627\u0628\u064A\u0629 \u0645\u0639 \u0627\u0644\u0641\u0631\u0642 \u0627\u0644\u062A\u064A \u062A\u0628\u0646\u064A\u0647\u0627."
    },
    photos: [
      {
        src: "/events/leap-2026/gate.webp",
        caption: {
          en: "LEAP 2026 \u2014 Into New Worlds",
          ar: "\u0644\u064A\u0628 \u0662\u0660\u0662\u0666 \u2014 \u0646\u062D\u0648 \u0639\u0648\u0627\u0644\u0645 \u062C\u062F\u064A\u062F\u0629"
        }
      },
      {
        src: "/events/leap-2026/optimus.webp",
        caption: {
          en: "Meeting Tesla Optimus",
          ar: "\u0644\u0642\u0627\u0621 \u0631\u0648\u0628\u0648\u062A \u062A\u0633\u0644\u0627 \u0623\u0648\u0628\u062A\u064A\u0645\u0648\u0633"
        }
      },
      {
        src: "/events/leap-2026/humain.webp",
        caption: {
          en: "HUMAIN's AI showcase",
          ar: "\u0645\u0639\u0631\u0636 \u0647\u064A\u0648\u0645\u0627\u064A\u0646 \u0644\u0644\u0630\u0643\u0627\u0621 \u0627\u0644\u0627\u0635\u0637\u0646\u0627\u0639\u064A"
        }
      },
      {
        src: "/events/leap-2026/main-hall.webp",
        caption: {
          en: "The main hall \u2014 Cisco, Microsoft, Huawei",
          ar: "\u0627\u0644\u0642\u0627\u0639\u0629 \u0627\u0644\u0631\u0626\u064A\u0633\u064A\u0629 \u2014 \u0633\u064A\u0633\u0643\u0648 \u0648\u0645\u0627\u064A\u0643\u0631\u0648\u0633\u0648\u0641\u062A \u0648\u0647\u0648\u0627\u0648\u064A"
        }
      },
      {
        src: "/events/leap-2026/leap-5.webp",
        caption: {
          en: "LEAP's fifth edition",
          ar: "\u0627\u0644\u0646\u0633\u062E\u0629 \u0627\u0644\u062E\u0627\u0645\u0633\u0629 \u0645\u0646 \u0644\u064A\u0628"
        }
      }
    ]
  }
];

// src/data/projects/index.json
var projects_default = [
  "twlm-pos",
  "aa-tourism",
  "scmborba",
  "docean-fisheries",
  "my-portfolio",
  "gala-travels",
  "mian-travels",
  "ain-saas",
  "city-arrivals",
  "mtlnation",
  "tdm",
  "eims",
  "lms"
];

// src/data/projects/twlm-pos.json
var twlm_pos_default = {
  id: "twlm-pos",
  title: "TWLM - POS",
  subtitle: "Point of Sale System with Loyalty & Wallet Integrations",
  description: [
    "TWLM - POS \u2013 Comprehensive Point of Sale System",
    [
      "A comprehensive POS and CMS platform for businesses \u2014 Gulf tax integrations, inventory, loyalty, gift cards, customizable e-menu storefronts, and 30+ CMS features. B2B2C.",
      "Improved the overall UI/UX, making features more intuitive and user-friendly, which reduced support center requests by approximately 70%.",
      "Designed and developed loyalty program features including a Loyalty Points System, Loyalty Cards, a Gift Card System with Apple Wallet and Google Wallet integration, and real-time notification support.",
      "Built a centralized promotional messaging system with Apple Wallet loyalty passes, smart geo-location targeting, and branch-based tracking and visibility.",
      "Developed a dynamic Page Builder and a Flutter-based mobile application that allows businesses to create customizable storefront pages and enables customers to place orders online easily.",
      "Optimized backend APIs, reducing latency by approximately 64% and improving system performance.",
      "Used Prisma ORM with PostgreSQL for schema migrations and faster data access; added RBAC with OAuth2/JWT and SSO for multi-role access.",
      "Built webhook-driven workflows for wallet updates and notifications, and integrated CRM plus Gulf payment gateways (MyFatoorah, Moyasar).",
      "Spearheaded OpenRouter AI (DeepSeek) integration for smart menu search and AI-based analysis of restaurant data.",
      "Refactored a large portion of the codebase\u2014improved code structure and maintainability, eliminated side effects caused by rapid development, and enhanced overall application stability."
    ]
  ],
  metrics: [
    {
      value: "~70%",
      label: "fewer support requests"
    },
    {
      value: "~64%",
      label: "lower API latency"
    },
    {
      value: "30+",
      label: "CMS features shipped"
    }
  ],
  technologies: [
    "React",
    "Flutter",
    "NestJS",
    "Fastify",
    "Node",
    "Prisma",
    "PostgreSQL",
    "Apple Wallet",
    "Google Wallet",
    "REST APIs",
    "Zustand",
    "TanStack Query",
    "OpenRouter"
  ],
  imageUrl: "/projects-media/twlm-pos/main.webp",
  projectUrl: "https://twlm.solutions",
  githubUrl: "https://github.com/Twlm-App/twlm-solutions",
  githubBackendUrl: "https://github.com/Twlm-App/twlm-solutions-backend",
  repoPublic: false,
  media: [
    "main.webp",
    "img1.webp",
    "img2.webp"
  ],
  featured: true,
  featuredMetric: 1,
  productUrl: "https://twlm.solutions/pos",
  experienceId: "twlm",
  teamSize: "",
  diagrams: [
    "architecture",
    "stackFlow",
    "walletSequence",
    "queue",
    "walletPass"
  ],
  caseStudy: {
    summary: "Restaurant POS, loyalty, wallet passes and AI menu search for Gulf retail \u2014 a B2B2C platform I designed and built from architecture to production.",
    problem: [
      "Businesses needed one B2B2C platform for POS and CMS: Gulf tax integrations, inventory, loyalty, gift cards, customizable e-menu storefronts and 30+ CMS features.",
      "Loyalty cards, gift cards and promotions had to live in customers' Apple Wallet and Google Wallet and stay up to date in real time."
    ],
    role: [
      "Senior Software Engineer (full stack): designed and built the restaurant POS platform with integrated loyalty, promotions and wallet features, from architecture through production delivery.",
      "Designed and developed the loyalty features: a loyalty points system, loyalty cards, and a gift card system with Apple Wallet and Google Wallet integration and real-time notification support.",
      "Built a centralized promotional messaging system with Apple Wallet loyalty passes, smart geo-location targeting, and branch-based tracking and visibility.",
      "Developed a dynamic, block-based page builder and a Flutter mobile app, so businesses create their own menus and storefront pages without developer help and customers can place orders online.",
      "Spearheaded the OpenRouter AI (DeepSeek) integration for smart menu search and AI-based analysis of restaurant data.",
      "Improved the overall UI/UX, making features more intuitive and user-friendly."
    ],
    architecture: [
      "API: NestJS on Fastify, serving REST APIs to the React web apps, the storefronts and the Flutter mobile app.",
      "Data: Prisma ORM on PostgreSQL, with schema migrations and query optimization for faster data access.",
      "Background work: webhook-driven, event-based workflows; Redis-backed BullMQ workers process notification and wallet-update jobs asynchronously.",
      "Access: RBAC with OAuth2/JWT authentication and SSO for multi-role access across the platform.",
      "Integrations: Apple Wallet and Google Wallet passes, Gulf payment gateways (MyFatoorah, Moyasar), and CRM and leasing platforms to keep customer and business data in sync.",
      "Frontend: React with Zustand and TanStack Query.",
      "AI: OpenRouter (DeepSeek) for smart menu search and AI-based analysis of restaurant data."
    ],
    challenges: [
      "Stability after rapid development: refactored a large portion of the codebase to improve structure and maintainability, eliminate side effects caused by rapid development, and make the application more stable.",
      "API performance: optimized the backend APIs, reducing latency by ~64%.",
      "Real-time wallet passes and notifications: triggered by webhook flows and processed asynchronously as jobs by Redis-backed BullMQ workers.",
      "Support load: reworked core user flows based on support data."
    ],
    results: [
      "~70% fewer customer support requests after reworking core flows and the overall UI/UX.",
      "~64% lower API latency and better overall system performance.",
      "30+ CMS features shipped on one B2B2C platform.",
      "Four loyalty features \u2014 points, loyalty passes, gift cards and discount coupons \u2014 with Apple Wallet and Google Wallet passes and real-time updates.",
      "A more maintainable and stable codebase."
    ],
    next: [],
    measured: ""
  },
  _draft: {
    architectureWhy: "TODO(moiez): confirm or rewrite before this is shown anywhere. Draft rationale: NestJS for a modular, typed structure across many domains (POS, loyalty, CMS, AI); Fastify as its HTTP adapter for lower overhead; Prisma for typed queries and versioned migrations on PostgreSQL; BullMQ on Redis to take wallet-pass updates and push notifications off the request path, with retries when Apple/Google calls fail; webhooks so external events (payments, CRM, wallet) drive updates instead of polling.",
    walletSequence: "TODO(moiez): confirm the wallet pass update sequence diagram (webhook \u2192 API \u2192 BullMQ job \u2192 worker \u2192 Apple/Google Wallet pass update \u2192 push to the customer's device) matches the real flow."
  },
  _todo: `TODO(moiez): fill teamSize (e.g. "4 engineers"), caseStudy.measured (how ~64% latency and ~70% support requests were measured, e.g. p95 before/after and over which period), caseStudy.next (what you'd do next), and confirm the _draft notes. Empty fields stay hidden on the site; add the same fields in Arabic under twlm-pos.caseStudy in src/i18n/projects-ar.json.`,
  walletPass: {
    front: "/projects-media/twlm-pos/pass-front.webp",
    back: null,
    _todo: 'TODO(moiez): replace with proper Apple Wallet screenshots (front and back, ~2x size) \u2014 set "front"/"back" to the new public paths and run npm run images. Today the front is cropped from img2 and the back is drawn from the facts in the case study.'
  },
  latency: {
    reduction: 64,
    percentile: "p95",
    beforeMs: null,
    afterMs: null,
    _todo: "TODO(moiez): set beforeMs/afterMs to the measured p95 API response times (ms) behind the ~64% figure; the bar then shows them instead of relative values"
  }
};

// src/data/projects/aa-tourism.json
var aa_tourism_default = {
  id: "aa-tourism",
  title: "AATourism",
  subtitle: "Flight Booking & Tour Planning Platform",
  description: [
    "AA Travel & Tourism \u2013 Flight Booking Platform",
    [
      "A flight booking and tour-planning platform integrated with IATA codes, Sabre, and Amadeus for real-time flight data.",
      "Developed high-quality UI focused on UX, animations, and seamless booking journeys.",
      "Forms, flight lists, and booking steps stay interactive but simple so users don\u2019t get lost.",
      "Worked closely with backend teams to deliver reliable, consistent booking experiences on mobile and desktop.",
      "Kept the visuals clean and consistent with the brand colors and style."
    ]
  ],
  technologies: [
    "NuxtJs",
    "Vuex",
    "Buefy",
    "Bootstrap",
    "JavaScript",
    "SCSS",
    "Sabre",
    "Amadeus"
  ],
  imageUrl: "/projects-media/aa-tourism/cover.webp",
  projectUrl: "http://aatourism.ca/",
  githubUrl: "https://github.com/moiezdev/AAtourism",
  repoPublic: true,
  media: [
    "cover.webp",
    "main-framed.webp",
    "img1-framed.webp",
    "img2-framed.webp",
    "img3-framed.webp",
    "img4-framed.webp"
  ],
  group: "client",
  caseStudy: {
    summary: "A flight booking and tour-planning platform for a Canadian travel agency, wired to Sabre and Amadeus for real-time flight data.",
    problem: [
      "Travellers needed to search, compare and book real flights and tours without getting lost in a complex booking journey.",
      "Flight data had to come live from global distribution systems (Sabre, Amadeus) using IATA codes, on desktop and mobile."
    ],
    role: [
      "Frontend lead at Creative Inter Tech for the B2B travel platforms (AA Tourism, City Arrivals).",
      "Built the booking journey in Nuxt: search forms, flight lists, filters and step-by-step booking.",
      "Worked with the backend team so live GDS data reached the UI reliably and consistently."
    ],
    architecture: [
      "Nuxt (Vue) frontend with Vuex for search and booking state.",
      "Buefy and Bootstrap components on a custom SCSS theme in the brand's colours.",
      "Flight search and availability through Sabre and Amadeus, mapped by IATA codes."
    ],
    challenges: [
      "Keeping a multi-step booking flow simple while showing a lot of live flight data.",
      "Consistent behaviour across mobile and desktop with real-time results."
    ],
    results: [
      "Live platform at aatourism.ca with real-time flight search and booking.",
      "Part of the B2B travel platforms serving 10K+ monthly users."
    ],
    next: [],
    measured: ""
  },
  metrics: [
    {
      value: "10K+",
      label: "monthly users across the B2B travel platforms"
    },
    {
      value: "2",
      label: "live GDS integrations (Sabre, Amadeus)"
    }
  ],
  experienceId: "creative-inter-tech",
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/scmborba.json
var scmborba_default = {
  id: "scmborba",
  title: "Scmborba",
  subtitle: "Social Services Website",
  description: [
    "Santa Casa da Miseric\xF3rdia de Borba \u2013 Institutional Website",
    [
      "Built and maintained full-stack features using Node.js, Express.js, and Vue.js/Nuxt.js, focusing on performance, usability, and maintainability.",
      "Developed responsive, user-focused interfaces with smooth interactions and translated Figma/XD into production UI.",
      "Designed backend APIs and optimized data handling, refining queries and application logic for better system efficiency.",
      "Collaborated with the team to modernize the visual identity of a non-profit social services institution, ensuring the platform clearly communicates its mission, services, and community initiatives.",
      "Optimized performance and usability for a wide audience, including elderly users and families seeking social support."
    ]
  ],
  technologies: [
    "Vue",
    "NuxtJs",
    "Node",
    "Express",
    "TailwindCSS",
    "JavaScript"
  ],
  imageUrl: "/projects-media/scmborba/cover.webp",
  projectUrl: "http://scmborba.pt",
  media: [
    "cover.webp",
    "main-framed.webp",
    "img1-framed.webp",
    "img2-framed.webp",
    "img3-framed.webp",
    "img4-framed.webp"
  ],
  repoPublic: false,
  group: "client",
  caseStudy: {
    summary: "The website of Santa Casa da Miseric\xF3rdia de Borba, a Portuguese social-services institution \u2014 full stack with Vue/Nuxt and Node/Express.",
    problem: [
      "A non-profit needed a modern site that clearly communicates its mission, services and community work.",
      "The audience includes elderly users and families looking for support, so it had to be simple and fast."
    ],
    role: [
      "Built and maintained full-stack features with Node.js, Express and Vue/Nuxt.",
      "Translated Figma/XD designs into responsive, production UI.",
      "Designed backend APIs and refined queries and application logic."
    ],
    architecture: [
      "Nuxt (Vue) front end styled with Tailwind CSS.",
      "Node.js and Express API serving the site's content."
    ],
    challenges: [
      "Usability and performance for a wide audience, including elderly users."
    ],
    results: [
      "Live at scmborba.pt with a modernised visual identity.",
      "Faster, more efficient data handling after query and logic refinements."
    ],
    next: [],
    measured: ""
  },
  experienceId: "scm-borba",
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/docean-fisheries.json
var docean_fisheries_default = {
  id: "docean-fisheries",
  title: "D\u2019Ocean Fisheries",
  subtitle: "Seafood Supplier Website",
  description: [
    "D\u2019Ocean Fisheries \u2013 Seafood Supplier Website",
    [
      "Created a fresh and simple frontend so customers can easily explore different seafood categories like live, frozen, and fillets.",
      "Designed the pages to be responsive, so everything looks clean and easy to use on both desktop and mobile screens.",
      "Added product sections with quick links and quote/contact forms to make browsing and inquiries straightforward.",
      "Focused on clear visuals, spacing, and smooth navigation so the site feels professional without being overwhelming.",
      "Worked with imagery, colors, and layout to reflect the brand identity of a seafood supplier."
    ]
  ],
  technologies: [
    "HTML5",
    "CSS3",
    "JavaScript"
  ],
  imageUrl: "/projects-media/docean-fisheries/cover.webp",
  projectUrl: "https://doceanfisheries.com/",
  media: [
    "cover.webp",
    "main-framed.webp"
  ],
  repoPublic: false,
  group: "earlier",
  caseStudy: {
    summary: "A responsive website for a Bahrain seafood supplier, with product categories and quote forms.",
    problem: [
      "Customers needed to explore live, frozen and fillet products and send inquiries easily."
    ],
    role: [
      "Designed and built the front end, product sections, quick links and quote/contact forms."
    ],
    architecture: [
      "Hand-built HTML5, CSS3 and JavaScript \u2014 no framework needed for a fast, simple site."
    ],
    challenges: [
      "A professional look that stays clear and uncluttered."
    ],
    results: [
      "Live at doceanfisheries.com, responsive on desktop and mobile."
    ],
    next: [],
    measured: ""
  },
  metrics: [
    {
      value: "3",
      label: "seafood categories: live, frozen and fillets"
    }
  ],
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/my-portfolio.json
var my_portfolio_default = {
  id: "my-portfolio",
  title: "Portfolio Website",
  subtitle: "My Personal Portfolio",
  description: [
    "MoezDev \u2013 Personal Portfolio Website",
    [
      "Built my personal portfolio from scratch to showcase my projects, skills, and experience as a frontend developer.",
      "Focused on creating a clean, responsive, and intuitive design that works smoothly on both desktop and mobile devices.",
      "Added interactive elements like project previews and smooth animations to make the site feel dynamic and engaging.",
      "Optimized the website for fast loading and a seamless user experience, keeping performance and accessibility in mind.",
      "Worked closely on the overall look and feel, making sure the design reflects my personal style and professional brand."
    ]
  ],
  technologies: [
    "React",
    "TailwindCSS",
    "JavaScript",
    "Redux Toolkit"
  ],
  imageUrl: "/projects-media/portfolio/cover.webp",
  githubUrl: "https://github.com/moiezdev/my-portfolio-react",
  repoPublic: true,
  media: [
    "cover.webp",
    "main-framed.webp"
  ],
  group: "earlier",
  caseStudy: {
    summary: "The first version of this portfolio \u2014 React, Tailwind CSS and Redux Toolkit, built from scratch.",
    problem: [
      "A place to show projects, skills and experience that loads fast and feels alive."
    ],
    role: [
      "Designed and built it end to end: project previews, animations and responsive layouts."
    ],
    architecture: [
      "React with Redux Toolkit for state and Tailwind CSS for styling."
    ],
    challenges: [
      "Rich interactions without hurting load time or accessibility."
    ],
    results: [
      "The foundation the current moiez.dev grew from."
    ],
    next: [],
    measured: ""
  },
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/gala-travels.json
var gala_travels_default = {
  id: "gala-travels",
  title: "Gala Travels",
  subtitle: "Flight, Hotel, Vacation & Cruise Booking",
  description: [
    "Gala Travels \u2013 Travel Agency Booking Platform",
    [
      "A travel-agency platform for booking flights, hotels, vacations, and cruises (galatravels.com).",
      "Frontend built with Vue/Nuxt, with a Laravel backend powering booking flows.",
      "Interactive booking forms, listings, and itinerary views designed to stay simple for agents and travelers.",
      "The site adapts to mobile and desktop, handling booking data without friction.",
      "Kept visuals consistent with the brand and the interface approachable."
    ]
  ],
  technologies: [
    "NuxtJs",
    "Vue",
    "Laravel",
    "Buefy",
    "Bootstrap",
    "JavaScript",
    "SCSS"
  ],
  imageUrl: "/projects-media/gala-travels/cover.webp",
  githubUrl: "https://github.com/moiezdev/gala-saber",
  repoPublic: true,
  media: [
    "cover.webp",
    "main-framed.webp",
    "img1-framed.webp"
  ],
  group: "client",
  caseStudy: {
    summary: "A travel-agency platform for booking flights, hotels, vacations and cruises \u2014 Vue/Nuxt on a Laravel backend.",
    problem: [
      "Agents and travellers needed one place to book four kinds of travel without the interface getting complicated."
    ],
    role: [
      "Built the Vue/Nuxt front end: booking forms, listings and itinerary views.",
      "Connected the booking flows to the Laravel backend."
    ],
    architecture: [
      "Nuxt (Vue) front end with Buefy and Bootstrap on SCSS.",
      "Laravel backend powering the booking flows."
    ],
    challenges: [
      "Four booking types with different data, in one consistent and approachable UI."
    ],
    results: [
      "Responsive booking flows for flights, hotels, vacations and cruises."
    ],
    next: [],
    measured: ""
  },
  metrics: [
    {
      value: "4",
      label: "booking types: flights, hotels, vacations, cruises"
    }
  ],
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/mian-travels.json
var mian_travels_default = {
  id: "mian-travels",
  title: "Mian's Travels",
  subtitle: "Flight Booking Platform",
  description: [
    "Mian's Travels \u2013 Flight Booking Platform",
    [
      "Built at Creative Inter Tech \u2014 a flight booking site using Sabre API, made to feel simple and intuitive for users.",
      "Frontend made with Nuxt 2, Vue, Buefy, Bootstrap, including small animations for better interactions.",
      "Booking forms, flight searches, and listings are straightforward and easy to navigate.",
      "Works well on mobile and desktop, fetching data from Sabre API without any hiccups.",
      "Focused on keeping the design clean, readable, and consistent with the brand style."
    ]
  ],
  technologies: [
    "NuxtJs",
    "Vue",
    "Buefy",
    "Bootstrap",
    "JavaScript",
    "SCSS",
    "Sabre"
  ],
  imageUrl: "/projects-media/mian-travels/cover.webp",
  githubUrl: "https://github.com/moiezdev/MiansTravels",
  repoPublic: false,
  media: [
    "cover.webp",
    "main-framed.webp",
    "img1-framed.webp"
  ],
  group: "client",
  caseStudy: {
    summary: "A flight booking platform on the Sabre API, built at Creative Inter Tech to feel simple and intuitive.",
    problem: [
      "Travellers needed a straightforward way to search flights and book, with data coming live from Sabre."
    ],
    role: [
      "Built the Nuxt 2 front end: flight search, listings and booking forms.",
      "Connected the UI to Sabre API data and kept it reliable on mobile and desktop."
    ],
    architecture: [
      "Nuxt 2 (Vue) with Buefy and Bootstrap components on SCSS.",
      "Live flight data from the Sabre API.",
      "Small, purposeful animations to guide users through booking."
    ],
    challenges: [
      "Turning raw GDS data into clean, readable flight results."
    ],
    results: [
      "A clean, brand-consistent booking flow backed by live Sabre data."
    ],
    next: [],
    measured: ""
  },
  experienceId: "creative-inter-tech",
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/ain-saas.json
var ain_saas_default = {
  id: "ain-saas",
  title: "Ain Saas",
  subtitle: "Ecommerce Website",
  description: [
    "Ain Saiss \u2013 Water Utility / Institutional Website",
    [
      "Made a simple and modern frontend to show the services and info clearly.",
      "Works on desktops and phones, and everything adjusts nicely depending on screen size.",
      "Added small interactive bits like menus and cards to make browsing a little more fun.",
      "Tried to keep it fast and easy to use for everyone, including people who use assistive tech.",
      "Worked with the team to keep colors, fonts, and visuals consistent with the brand."
    ]
  ],
  technologies: [
    "HTML5",
    "SCSS",
    "JavaScript"
  ],
  imageUrl: "/projects-media/ain-saas/cover.webp",
  projectUrl: "https://ain-saiss.ma",
  media: [
    "cover.webp",
    "main-framed.webp",
    "img1-framed.webp",
    "img2-framed.webp",
    "img3-framed.webp"
  ],
  repoPublic: false,
  group: "earlier",
  caseStudy: {
    summary: "A modern, accessible website for A\xEFn Sa\xEFss, a Moroccan mineral-water brand \u2014 products, services and brand content.",
    problem: [
      "The brand needed its products and information presented clearly on every screen size."
    ],
    role: [
      "Built the front end with interactive menus and cards, keeping it fast and accessible."
    ],
    architecture: [
      "HTML5, SCSS and JavaScript with a responsive, component-like structure."
    ],
    challenges: [
      "Accessibility for everyone, including people using assistive tech."
    ],
    results: [
      "A fast, consistent brand site that adapts to desktop and mobile."
    ],
    next: [],
    measured: ""
  },
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/city-arrivals.json
var city_arrivals_default = {
  id: "city-arrivals",
  title: "City Arrivals",
  subtitle: "Luxury Car Booking Platform",
  description: [
    "City Arrivals \u2013 Luxury Car Booking (cityarrivals.ca)",
    [
      "A luxury car booking platform based in Canada, built for B2B travel operations alongside AA Travel & Tourism.",
      "Focused on a seamless booking experience for premium vehicle rentals.",
      "Developed responsive layouts for reliable performance across devices.",
      "Integrated booking flows so users can schedule and manage rides easily.",
      "Kept brand consistency and fast, smooth navigation."
    ]
  ],
  technologies: [
    "HTML5",
    "SCSS",
    "JavaScript",
    "Jquery"
  ],
  imageUrl: "/projects-media/city-arrivals/cover.webp",
  projectUrl: "https://cityarrivals.ca",
  media: [
    "cover.webp",
    "main-framed.webp",
    "img1-framed.webp",
    "img2-framed.webp"
  ],
  repoPublic: false,
  group: "earlier",
  caseStudy: {
    summary: "Luxury car booking for a Canadian operator, built for B2B travel operations alongside AA Travel & Tourism.",
    problem: [
      "Customers needed to book premium vehicles \u2014 point-to-point, hourly or airport \u2014 quickly and with confidence."
    ],
    role: [
      "Built the booking front end at Creative Inter Tech as part of the B2B travel platforms.",
      "Integrated the booking flow so users can schedule and manage rides."
    ],
    architecture: [
      "Responsive HTML5 and SCSS layouts with jQuery-driven booking interactions.",
      "Location search and map-based pickup/drop-off feeding the booking flow."
    ],
    challenges: [
      "A premium feel with fast, smooth navigation on every device."
    ],
    results: [
      "Live at cityarrivals.ca.",
      "Part of the B2B travel platforms serving 10K+ monthly users."
    ],
    next: [],
    measured: ""
  },
  metrics: [
    {
      value: "10K+",
      label: "monthly users across the B2B travel platforms"
    }
  ],
  experienceId: "creative-inter-tech",
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/mtlnation.json
var mtlnation_default = {
  id: "mtlnation",
  title: "MTLnation",
  subtitle: "Vue.js Based Website",
  description: [
    "MTLnation \u2013 Vue.js Web Platform",
    [
      "Built the site using Vue.js with a focus on keeping everything fast and responsive.",
      "Structured the pages as reusable Vue components, so it\u2019s easier to maintain and extend later.",
      "Added dynamic sections like news, events, and media content with smooth transitions and animations.",
      "Integrated forms and interactive parts so users can connect, subscribe, or explore content without issues.",
      "Kept the design clean with consistent colors, fonts, and spacing to match the brand\u2019s modern look."
    ]
  ],
  technologies: [
    "Vue",
    "JavaScript",
    "SCSS",
    "Bootstrap"
  ],
  imageUrl: "/projects-media/mtlnation/cover.webp",
  projectUrl: "https://mtlnation.com",
  media: [
    "cover.webp",
    "main-framed.webp"
  ],
  repoPublic: false,
  group: "client",
  caseStudy: {
    summary: "A Vue.js web platform for web novels \u2014 library, leaderboard and reading pages built from reusable components.",
    problem: [
      "Readers needed to browse, discover and follow content smoothly, with dynamic sections that stay fast."
    ],
    role: [
      "Built the site in Vue.js with reusable components.",
      "Added dynamic sections (news, events, media) with smooth transitions, plus forms and interactive parts."
    ],
    architecture: [
      "Vue.js single-page app structured as reusable components.",
      "Bootstrap and SCSS for a consistent, modern design system."
    ],
    challenges: [
      "Lots of dynamic content without losing speed or responsiveness."
    ],
    results: [
      "A component-based codebase that's easy to maintain and extend."
    ],
    next: [],
    measured: ""
  },
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/tdm.json
var tdm_default = {
  id: "tdm",
  title: "TDM",
  subtitle: "Civil Engineering & Project Management Website",
  description: [
    "TDM \u2013 Engenharia & Gest\xE3o de Projetos",
    [
      "Developed the frontend for TDM\u2019s corporate website, presenting the company\u2019s civil engineering and project management services.",
      "Structured clear sections for services, projects, and contact, so visitors quickly understand what TDM offers.",
      "Made the site responsive, adapting well across desktop and mobile devices.",
      "Used a clean and professional design approach to reflect TDM\u2019s reliability and technical expertise.",
      "Focused on keeping the site simple to navigate while aligning visuals with the company\u2019s brand identity."
    ]
  ],
  technologies: [
    "HTML5",
    "CSS3",
    "JavaScript"
  ],
  imageUrl: "/projects-media/tdm/cover.webp",
  githubUrl: "https://github.com/moiezdev/tdm",
  repoPublic: true,
  media: [
    "cover.webp",
    "main-framed.webp",
    "img1-framed.webp",
    "img2-framed.webp",
    "img3-framed.webp",
    "img4-framed.webp"
  ],
  group: "earlier",
  caseStudy: {
    summary: "The corporate website of TDM, a Portuguese civil-engineering and project-management company.",
    problem: [
      "Visitors needed to understand TDM's services and projects quickly and get in touch."
    ],
    role: [
      "Developed the front end with clear sections for services, projects and contact."
    ],
    architecture: [
      "HTML5, CSS3 and JavaScript with a responsive layout."
    ],
    challenges: [
      "Conveying technical reliability through a clean, simple design."
    ],
    results: [
      "A professional, responsive site aligned with TDM's brand."
    ],
    next: [],
    measured: ""
  },
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/eims.json
var eims_default = {
  id: "eims",
  title: "EIMS",
  subtitle: "AI-Powered Learning Management System (In Progress)",
  description: [
    "EIMS \u2013 AI-Powered Learning Management System",
    [
      "Currently developing an AI-powered learning management system with a .NET backend.",
      "Helps students select the right courses based on their interests and goals, using AI-driven recommendations to personalize the learning path.",
      "Backend built with ASP.NET, Entity Framework, and PostgreSQL for a robust, scalable foundation."
    ]
  ],
  technologies: [
    "ASP.NET",
    "C# (C Sharp)",
    "Entity Framework",
    "PostgreSQL"
  ],
  imageUrl: "/projects-media/eims/main.webp",
  githubUrl: "https://github.com/moiezdev/EIMS.WebAPI",
  repoPublic: true,
  media: [
    "main.webp"
  ],
  screenshot: false,
  status: "in-progress",
  caseStudy: {
    summary: "An AI-powered learning management system in progress, with a .NET backend that recommends courses.",
    problem: [
      "Students struggle to pick the right courses for their interests and goals."
    ],
    role: [
      "Designing and building the system and its recommendation logic."
    ],
    architecture: [
      "ASP.NET and Entity Framework on PostgreSQL.",
      "AI-driven recommendations to personalise each learning path."
    ],
    challenges: [],
    results: [
      "In progress."
    ],
    next: [],
    measured: ""
  },
  diagrams: [
    "stackFlow"
  ]
};

// src/data/projects/lms.json
var lms_default = {
  id: "lms",
  title: "LMS",
  subtitle: "Learning Management System FullStack (Under Development)",
  description: [
    "LMS \u2013 Learning Management System",
    [
      "This is my own project to make learning easier online, with features like quizzes, dashboards, and progress tracking.",
      "The interface is simple and works well on both desktop and mobile, so learners can use it anywhere.",
      "Added interactive parts so users can see their progress and navigate courses without confusion.",
      "Tried to keep everything fast and clean so it doesn\u2019t feel slow even with lots of content.",
      "Connected it with backend stuff like Node and MongoDB to save and manage all the data smoothly."
    ]
  ],
  technologies: [
    "HTML5",
    "SCSS",
    "JavaScript",
    "React",
    "Redux Toolkit",
    "Node",
    "Express",
    "MongoDB"
  ],
  imageUrl: "/projects-media/lms/main.webp",
  githubUrl: "https://github.com/moiezdev/LMS",
  repoPublic: true,
  media: [
    "main.webp"
  ],
  listed: false,
  _todo: 'TODO(moiez): replace main.webp/main.jpg (the image reads "Dashobard"), then delete "listed": false'
};

// src/data/projects.js
var projectsById = {
  "twlm-pos": twlm_pos_default,
  "aa-tourism": aa_tourism_default,
  scmborba: scmborba_default,
  "docean-fisheries": docean_fisheries_default,
  "my-portfolio": my_portfolio_default,
  "gala-travels": gala_travels_default,
  "mian-travels": mian_travels_default,
  "ain-saas": ain_saas_default,
  "city-arrivals": city_arrivals_default,
  mtlnation: mtlnation_default,
  tdm: tdm_default,
  eims: eims_default,
  lms: lms_default
};
var knownSkills = new Set(skills_default.flatMap((category) => category.items));
var allProjects = projects_default.map((id) => {
  const project = projectsById[id];
  if (!project) {
    throw new Error(`Missing project JSON for id: ${id}`);
  }
  const unknownTech = project.technologies.filter((tech) => !knownSkills.has(tech));
  if (unknownTech.length) {
    console.warn(
      `[data/projects] "${project.id}" uses tech not in skills.json:`,
      unknownTech.join(", ")
    );
  }
  if (project.repoPublic !== true) {
    const { githubUrl: _g, githubBackendUrl: _b, ...rest } = project;
    return rest;
  }
  return project;
});
var projects = allProjects.filter((project) => project.listed !== false);

// src/data/index.js
var about = {
  ...about_default,
  description: (about_default.description || []).map(withExperienceYears)
};

// src/lib/contextBuilder.js
var LOW_PRIORITY = new Set(chatbot_default.lowPriorityProjectIds || []);
var KEYWORDS = chatbot_default.projectNavKeywords || {};
var PAGE_NAMES = {
  "/": "Home",
  "/works": "All works",
  "/experience": "Experience",
  "/about": "About",
  "/contact": "Contact",
  "/cv": "CV"
};
function projectLines(project, limit = 12) {
  const lines = [];
  for (const block of project.description || []) {
    const items = Array.isArray(block) ? block : [block];
    for (const line of items) {
      if (typeof line === "string" && line.trim()) lines.push(line.trim());
      if (lines.length >= limit) return lines;
    }
  }
  return lines;
}
var projectIndex = (project) => ({
  name: project.title,
  path: `/works/${project.id}`,
  what: project.subtitle,
  stack: (project.technologies || []).slice(0, 5),
  ...LOW_PRIORITY.has(project.id) ? { note: "in progress / only mention if asked" } : {}
});
var projectDetail = (project) => ({
  name: project.title,
  path: `/works/${project.id}`,
  what: project.subtitle,
  ...project.caseStudy ? {
    summary: project.caseStudy.summary,
    architecture: project.caseStudy.architecture,
    role: project.caseStudy.role,
    results: project.caseStudy.results
  } : {},
  ...project.metrics?.length ? { metrics: project.metrics.map((m) => `${m.value} ${m.label}`) } : {},
  details: projectLines(project, 10).map((l) => l.slice(0, 220)),
  stack: project.technologies || [],
  live: project.projectUrl || void 0,
  github: project.githubUrl || void 0
});
function selectRelevantProjects(query = "", { exclude } = {}) {
  const q = String(query).toLowerCase();
  const scored = projects.filter((p) => p.id !== exclude).map((p) => {
    let score = 0;
    if (q.includes(p.title.toLowerCase()) || q.includes(p.id)) score += 10;
    for (const k of KEYWORDS[p.id] || []) {
      if (String(k).length > 2 && q.includes(String(k).toLowerCase())) score += 5;
    }
    for (const tech of p.technologies || []) {
      if (tech.length > 2 && q.includes(tech.toLowerCase())) score += 2;
    }
    if (/travel|flight|booking|tour/.test(q) && /travel|tourism|arrival/i.test(`${p.title} ${p.id}`)) score += 4;
    if (LOW_PRIORITY.has(p.id)) score -= 3;
    return { project: p, score };
  }).filter((row) => row.score > 0).sort((a, b) => b.score - a.score);
  return scored.slice(0, 3).map((r) => r.project);
}
function buildContext(question = "", { path = "/", previousQuestion = "" } = {}) {
  const profile = chatbot_default.profile || {};
  const years = getExperienceYears(profile.careerStart ? new Date(profile.careerStart) : void 0);
  const viewingId = path.match(/^\/works\/([^/]+)/)?.[1];
  const viewing = viewingId ? projects.find((p) => p.id === viewingId) : null;
  let relevant = selectRelevantProjects(question, { exclude: viewing?.id });
  if (!relevant.length && previousQuestion) {
    relevant = selectRelevantProjects(previousQuestion, { exclude: viewing?.id });
  }
  const event = events_default?.[0];
  return {
    visitor: {
      currentPage: PAGE_NAMES[path] || (viewing ? `Project page: ${viewing.title}` : path),
      ...viewing ? { viewingProject: projectDetail(viewing) } : {}
    },
    identity: {
      name: profile.name,
      alsoKnownAs: profile.alsoKnownAs,
      title: profile.headline || about.subtitle,
      location: profile.location,
      experienceYears: years,
      summary: profile.identity,
      availability: "Open to senior full stack engineering and software architect roles, and to freelance/contract projects",
      workAuthorization: profile.iqama
    },
    // what each kind of visitor needs: recruiters get the pitch, clients get scope + how to start
    forRecruiters: chatbot_default.audiences?.recruiters,
    forClients: chatbot_default.audiences?.clients,
    experience: experience_default.map((job) => ({
      title: job.title,
      company: job.company,
      period: job.period,
      location: job.location,
      current: Boolean(job.current),
      summary: job.summary,
      highlights: (job.highlights || []).slice(0, 4).map((h) => h.slice(0, 180)),
      stack: (job.stack || []).slice(0, 8)
    })),
    relevantProjects: relevant.map(projectDetail),
    allProjects: projects.map(projectIndex),
    skills: Object.fromEntries(skills_default.map((c) => [c.category, c.items])),
    education: {
      degree: education_default.degree,
      school: education_default.school,
      period: education_default.period,
      languages: education_default.languages
    },
    ...event ? {
      events: [
        {
          name: event.name,
          place: event.place?.en,
          note: event.summary?.en,
          seen: event.photos.map((p) => p.caption?.en)
        }
      ]
    } : {},
    contact: {
      email: contacts_default.find((c) => c.platform === "Email")?.handle,
      phone: contacts_default.find((c) => c.platform === "Phone")?.handle,
      whatsapp: contacts_default.find((c) => c.platform === "WhatsApp")?.handle,
      github: contacts_default.find((c) => c.platform === "GitHub")?.handle,
      linkedin: contacts_default.find((c) => c.platform === "LinkedIn")?.handle,
      portfolio: profile.portfolioUrl,
      cvPage: "/cv"
    }
  };
}
export {
  buildContext,
  selectRelevantProjects
};
