import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiReact,
  SiFlutter,
  SiVuedotjs,
  SiNextdotjs,
  SiNuxt,
  SiDotnet,
  SiNodedotjs,
  SiNestjs,
  SiFastify,
  SiExpress,
  SiTailwindcss,
  SiMui,
  SiReactquery,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiGit,
  SiGithub,
  SiGitlab,
  SiVite,
  SiVercel,
  SiNetlify,
  SiApple,
  SiGooglepay,
  SiFigma,
  SiSketch,
  SiHtml5,
  SiCss,
  SiSass,
  SiJest,
  SiBootstrap,
  SiRedux,
  SiJquery,
  SiBuefy,
} from 'react-icons/si';
import { TbBrandCSharp, TbBrandAdobeXd } from 'react-icons/tb';
import {
  MdOutlineGroups,
  MdApi,
  MdFlight,
  MdOutlineInventory2,
  MdOutlineManageAccounts,
  MdOutlineDesignServices,
  MdOutlineFeaturedPlayList,
  MdOutlineDashboardCustomize,
  MdOutlineArchitecture,
  MdSecurity,
  MdSpeed,
  MdOutlineAllInclusive,
  MdOutlineCreditCard,
  MdOutlineHub,
  MdSmartToy,
} from 'react-icons/md';
import { RiBearSmileLine } from 'react-icons/ri';
import { BiData } from 'react-icons/bi';
import { SiPhp, SiLaravel, SiJira, SiTrello, SiPrisma, SiGithubcopilot, SiDocker, SiAnthropic } from 'react-icons/si';

export const skillIcons = {
  'Product Ownership': { Icon: MdOutlineInventory2, color: '#ffff00' },
  'Feature Ownership': { Icon: MdOutlineFeaturedPlayList, color: '#ffff00' },
  'Product Management': { Icon: MdOutlineManageAccounts, color: '#ffff00' },
  'Feature Management': { Icon: MdOutlineDashboardCustomize, color: '#ffff00' },
  'UI/UX Management': { Icon: MdOutlineDesignServices, color: '#ffff00' },
  'End-to-End Delivery': { Icon: MdOutlineAllInclusive, color: '#ffff00' },
  MVC: { Icon: MdOutlineArchitecture, color: '#abb2bf' },
  HMVC: { Icon: MdOutlineArchitecture, color: '#abb2bf' },
  MVP: { Icon: MdOutlineArchitecture, color: '#abb2bf' },
  MVVM: { Icon: MdOutlineArchitecture, color: '#abb2bf' },
  'Component Based': { Icon: MdOutlineArchitecture, color: '#61DAFB' },
  Microservices: { Icon: MdOutlineArchitecture, color: '#E0234E' },
  'Event-driven architecture': { Icon: MdOutlineArchitecture, color: '#ffff00' },
  Prisma: { Icon: SiPrisma, color: '#5A67D8' },
  RBAC: { Icon: MdSecurity, color: '#F59E0B' },
  OAuth2: { Icon: MdSecurity, color: '#4285F4' },
  OIDC: { Icon: MdSecurity, color: '#22C55E' },
  JWT: { Icon: MdSecurity, color: '#FB7185' },
  SSO: { Icon: MdOutlineManageAccounts, color: '#A78BFA' },
  Webhooks: { Icon: MdOutlineHub, color: '#06B6D4' },
  CRM: { Icon: MdOutlineManageAccounts, color: '#38BDF8' },
  MyFatoorah: { Icon: MdOutlineCreditCard, color: '#00A651' },
  Moyasar: { Icon: MdOutlineCreditCard, color: '#1B4D3E' },
  'GitHub Copilot': { Icon: SiGithubcopilot, color: '#FFFFFF' },
  'Context API': { Icon: SiReact, color: '#61DAFB' },
  Pinia: { Icon: SiVuedotjs, color: '#FFD859' },
  Laravel: { Icon: SiLaravel, color: '#FF2D20' },
  PHP: { Icon: SiPhp, color: '#777BB4' },
  'SQL Server': { Icon: BiData, color: '#CC2927' },
  'Code Splitting': { Icon: MdSpeed, color: '#ffff00' },
  'Lazy Loading': { Icon: MdSpeed, color: '#06B6D4' },
  Caching: { Icon: MdSpeed, color: '#22C55E' },
  'Database Indexing': { Icon: BiData, color: '#4169E1' },
  LINQ: { Icon: TbBrandCSharp, color: '#239120' },
  Docker: { Icon: SiDocker, color: '#2496ED' },
  OpenRouter: { Icon: MdSmartToy, color: '#ffff00' },
  DeepSeek: { Icon: MdSmartToy, color: '#4D6BFE' },
  'Agentic AI': { Icon: MdSmartToy, color: '#ffff00' },
  Cursor: { Icon: MdSmartToy, color: '#FFFFFF' },
  Claude: { Icon: SiAnthropic, color: '#D4A27F' },
  'Authentication & Authorization': { Icon: MdSecurity, color: '#F59E0B' },
  Jira: { Icon: SiJira, color: '#0052CC' },
  Trello: { Icon: SiTrello, color: '#0052CC' },
  'CI/CD': { Icon: SiGitlab, color: '#FC6D26' },
  Scrum: { Icon: MdOutlineGroups, color: '#22C55E' },
  JavaScript: { Icon: SiJavascript, color: '#F7DF1E' },
  TypeScript: { Icon: SiTypescript, color: '#3178C6' },
  'C# (C Sharp)': { Icon: TbBrandCSharp, color: '#239120' },
  Python: { Icon: SiPython, color: '#3776AB' },
  React: { Icon: SiReact, color: '#61DAFB' },
  Flutter: { Icon: SiFlutter, color: '#02569B' },
  Vue: { Icon: SiVuedotjs, color: '#4FC08D' },
  NextJs: { Icon: SiNextdotjs, color: '#FFFFFF' },
  NuxtJs: { Icon: SiNuxt, color: '#00DC82' },
  'ASP.NET': { Icon: SiDotnet, color: '#512BD4' },
  DotNET: { Icon: SiDotnet, color: '#512BD4' },
  Node: { Icon: SiNodedotjs, color: '#339933' },
  NestJs: { Icon: SiNestjs, color: '#E0234E' },
  Fastify: { Icon: SiFastify, color: '#FFFFFF' },
  Express: { Icon: SiExpress, color: '#FFFFFF' },
  TailwindCSS: { Icon: SiTailwindcss, color: '#06B6D4' },
  MaterialUI: { Icon: SiMui, color: '#007FFF' },
  Zustand: { Icon: RiBearSmileLine, color: '#443E38' },
  'TanStack Query': { Icon: SiReactquery, color: '#FF4154' },
  MongoDB: { Icon: SiMongodb, color: '#47A248' },
  MySQL: { Icon: SiMysql, color: '#4479A1' },
  PostGreSQL: { Icon: SiPostgresql, color: '#4169E1' },
  Git: { Icon: SiGit, color: '#F05032' },
  GitHub: { Icon: SiGithub, color: '#FFFFFF' },
  GitLab: { Icon: SiGitlab, color: '#FC6D26' },
  Vite: { Icon: SiVite, color: '#646CFF' },
  Vercel: { Icon: SiVercel, color: '#FFFFFF' },
  Netlify: { Icon: SiNetlify, color: '#00C7B7' },
  'Apple Wallet': { Icon: SiApple, color: '#FFFFFF' },
  'Google Wallet': { Icon: SiGooglepay, color: '#4285F4' },
  Figma: { Icon: SiFigma, color: '#F24E1E' },
  'Adobe XD': { Icon: TbBrandAdobeXd, color: '#FF61F6' },
  Sketch: { Icon: SiSketch, color: '#F7B500' },
  HTML5: { Icon: SiHtml5, color: '#E34F26' },
  CSS3: { Icon: SiCss, color: '#1572B6' },
  SCSS: { Icon: SiSass, color: '#CC6699' },
  Bootstrap: { Icon: SiBootstrap, color: '#7952B3' },
  'Redux Toolkit': { Icon: SiRedux, color: '#764ABC' },
  Vuex: { Icon: SiVuedotjs, color: '#4FC08D' },
  Buefy: { Icon: SiBuefy, color: '#7957D5' },
  Jquery: { Icon: SiJquery, color: '#0769AD' },
  'Entity Framework': { Icon: BiData, color: '#512BD4' },
  Sabre: { Icon: MdFlight, color: '#E31837' },
  Amadeus: { Icon: MdFlight, color: '#1A73E8' },
  'REST APIs': { Icon: MdApi, color: '#00C853' },
  'Agile Methodologies': { Icon: MdOutlineGroups, color: '#22C55E' },
  'Test-Driven Development': { Icon: SiJest, color: '#C21325' },
};

/** Maps alternate project tech labels → canonical skillIcons keys */
const skillIconAliases = {
  'react.js': 'React',
  reactjs: 'React',
  'vue.js': 'Vue',
  vuejs: 'Vue',
  'node.js': 'Node',
  nodejs: 'Node',
  'nest.js': 'NestJs',
  nestjs: 'NestJs',
  nextjs: 'NextJs',
  'next.js': 'NextJs',
  nuxtjs: 'NuxtJs',
  'nuxt.js': 'NuxtJs',
  'nuxt 2': 'NuxtJs',
  nuxt: 'NuxtJs',
  html: 'HTML5',
  html5: 'HTML5',
  css: 'CSS3',
  css3: 'CSS3',
  sass: 'SCSS',
  scss: 'SCSS',
  'bootstrap 5': 'Bootstrap',
  bootstrap: 'Bootstrap',
  'asp.net': 'ASP.NET',
  'asp.net core': 'ASP.NET',
  dotnet: 'DotNET',
  '.net': 'DotNET',
  'c#': 'C# (C Sharp)',
  csharp: 'C# (C Sharp)',
  postgresql: 'PostGreSQL',
  'postgresql server': 'PostGreSQL',
  postgres: 'PostGreSQL',
  jquery: 'Jquery',
  'redux toolkit': 'Redux Toolkit',
  redux: 'Redux Toolkit',
  'entity framework': 'Entity Framework',
  'tanstack query': 'TanStack Query',
  'react query': 'TanStack Query',
  'apple wallet': 'Apple Wallet',
  'google wallet': 'Google Wallet',
  'rest apis': 'REST APIs',
  'rest api': 'REST APIs',
  prisma: 'Prisma',
  rbac: 'RBAC',
  oauth2: 'OAuth2',
  oauth: 'OAuth2',
  oidc: 'OIDC',
  jwt: 'JWT',
  sso: 'SSO',
  webhooks: 'Webhooks',
  webhook: 'Webhooks',
  crm: 'CRM',
  myfatoorah: 'MyFatoorah',
  moyasar: 'Moyasar',
  'github copilot': 'GitHub Copilot',
  copilot: 'GitHub Copilot',
  'event-driven architecture': 'Event-driven architecture',
  'event driven architecture': 'Event-driven architecture',
  docker: 'Docker',
  linq: 'LINQ',
  'database indexing': 'Database Indexing',
  openrouter: 'OpenRouter',
  deepseek: 'DeepSeek',
  'agentic ai': 'Agentic AI',
  cursor: 'Cursor',
  claude: 'Claude',
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  flutter: 'Flutter',
  fastify: 'Fastify',
  express: 'Express',
  tailwindcss: 'TailwindCSS',
  tailwind: 'TailwindCSS',
  materialui: 'MaterialUI',
  zustand: 'Zustand',
  mongodb: 'MongoDB',
  mysql: 'MySQL',
  vuex: 'Vuex',
  buefy: 'Buefy',
  sabre: 'Sabre',
  amadeus: 'Amadeus',
};

const normalizeTechName = (name) =>
  String(name || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ');

export const getSkillIcon = (name) => {
  if (!name) return null;
  if (skillIcons[name]) return skillIcons[name];

  const normalized = normalizeTechName(name);
  const aliasKey = skillIconAliases[normalized];
  if (aliasKey && skillIcons[aliasKey]) return skillIcons[aliasKey];

  // Case-insensitive match against canonical keys
  const direct = Object.keys(skillIcons).find((key) => normalizeTechName(key) === normalized);
  return direct ? skillIcons[direct] : null;
};
